version: '3.8'
services:
    orders-db:
        container_name: orders-db
        image: postgres:16.2
        restart: always
        ports:
          - 5432:5432
        volumes: 
          - ./postgres:/var/lib/postgresql/data
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=123456
          - POSTGRES_DB=ordersdb
